### ISSUE TITLE
Regarding updating OpenSSL to an appropriate version

### ISSUE THREAD

**Issue by clang-clang-clang** [coronalabs/plugins-source-openssl#1]
Related to https://github.com/coronalabs/corona/issues/534.

The current version of OpenSSL has many vulnerabilities and needs to be updated. And according to *[OpenSSL 1.1.1 End of Life](https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/)*, I have two questions:

About OpenSSL version:

1. Due to the outdated 1.0.2 series, the latest public version 1.0.2u still has many vulnerabilities (our colleagues have tried to update), so it is not recommended.
2. The 1.1.1 series will also stop public maintenance in September this year. Compared with take the 3.x series, the advantage is that compatibility issues may be relatively low, and there is less content to deal with. However, according to the recommendation, another upgrade will be required in half a year.
3. The 3.0 series is LTS and will be supported until September 2026, while the 3.1 series is not LTS and will be supported until March 2025.

About Apple Xcode version (related to binary architectures support):

1. Xcode 14, according to *[Apple submit - Build with Xcode 14.1](https://developer.apple.com/ios/submit/), starting April 2023, all iOS and iPadOS apps submitted to the App Store must be built with Xcode 14.1 and the iOS 16.1 SDK* (or later, AFAIK), which should already be in effect. However, Xcode 14 removed the 32-bit SDKs, and as a result, this plugin will not support game developers who do not need to be on the App Store.
2. Xcode 13 has better compatibility, but may not be necessary under Apple's policies?

IMO, the first step should be try upgrading to the OpenSSL 3.0 series. If there are compatibility issues with third-party libraries, then support for the latest version of 1.1.1 can be considered as a backup. For Xcode, I suggest using Xcode 14 for compilation.

Currently, we will follow the above approach to make an attempt and submit a PR at the appropriate time.

What do you think?

**Comment by Shchvova** [comment]
so... Building OpenSSL was never really the problem.
Biggest problem is that we have a combo of plugins, which are dependant on each other. It is basically combination of luasec, openssl and `lua-openssl` which causes the issues. Honestly I struggled with even updation from 1.02 to 1.1.0 with those libraries, because OpenSSL changes API so much :(

**Comment by clang-clang-clang** [comment]
So if I make some changes, can I push them directly to this repository? (Including some changes made to hg repository before, I need your answer in consideration of potential security and authorization issues.) Or should I send the compressed package back to you for your review before deciding whether to publish? thank you.

**Comment by Shchvova** [comment]
Yes. Feel free to restructure the repo as you see fit
